### ISSUE TITLE
Parameters at path roots are mishandled

### ISSUE THREAD

**Issue by delventhalz** [ikalnytskyi/sphinxcontrib-openapi#8]
`openapi2httpdomain` assumes all keys at the root level of paths are HTTP Methods, but according to the Open API spec, they can also be parameters which will be passed down to all methods at that route. For example, the following YAML will not build:

```
paths:
  /state/{merkel_root}:
    parameters:
      - $ref: "#/parameters/merkel_root"
    get:
      . . .
    post:
      . . .
```

**Comment by ikalnytskyi** [comment]
Thanks for reporting! Gotta take a look which *keys* are allowed in paths.
